name: Docker build/deploy image to Danubetech Nexus

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.circleci'
      - '**.md'
      - 'LICENSE'
      - 'MANIFEST.in'
      - 'NOTICES'
      - 'requirements**'
      - 'docs'
      - 'scripts'
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: universalresolver/universal-resolver-didcomm
  PATH_TO_DOCKERFILE: /docker/did_resolution_server.Dockerfile
  BUILD_CONTEXT: $GITHUB_WORKSPACE

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run build image action
        run: docker build -f "${{ env.BUILD_CONTEXT }}${{ env.PATH_TO_DOCKERFILE }}" -t "${{ env.IMAGE_NAME }}" "${{ env.BUILD_CONTEXT }}"
      - name: Login user to repo
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login "${{ env.REPO_NAME }}" -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push image
        run: docker push "${{ env.IMAGE_NAME }}"
